version: '3.1'

services:
    dbpostgres:
        image: postgres
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=AlTheOne
            - POSTGRES_PASSWORD=pgpass
        volumes:
            - ./database/postgres:/var/lib/postgresql
        networks:
            - net

    pgadmin:
        image: dpage/pgadmin4
        ports:
            - 9080:80
        environment:
            - PGADMIN_DEFAULT_EMAIL=altheone.official@gmail.com
            - PGADMIN_DEFAULT_PASSWORD=pass
        networks:
            - net

networks:
    net: