version: '3.1'

services:
  mysql:
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./mysqldb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql:db
    ports:
      - 8880:80
    environment:
      MYSQL_ROOT_PASSWORD: pass
    depends_on:
      - mysql